P8105 Homework 2
================
Xinzhuo Zhu
2026-10-07

# Problem 1

``` r
subway_df =
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  clean_names() |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    starts_with("route"),
    entry,
    vending,
    entrance_type,
    ada
  ) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

The cleaned subway dataset contains 1,868 observations and 19 variables.
The variables include subway line and station name, station latitude and
longitude, routes served, whether entry is allowed, vending
availability, entrance type, and ADA compliance. I cleaned the data by
standardizing variable names, selecting only the variables relevant to
this analysis, and converting the `entry` variable from character values
(“YES”/“NO”) to a logical variable.

These data are not completely tidy because the routes served by each
station are stored across multiple columns (`route1`, `route2`, etc.),
rather than in separate route number and route name variables.

``` r
distinct_stations =
  subway_df |>
  distinct(line, station_name)

nrow(distinct_stations)
```

    ## [1] 465

There are 465 distinct subway stations, where stations are identified
using both `line` and `station_name`.

``` r
ada_stations =
  subway_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name)

nrow(ada_stations)
```

    ## [1] 84

There are 84 ADA-compliant subway stations.

``` r
no_vending_entry_prop =
  subway_df |>
  filter(vending == "NO") |>
  summarize(
    proportion = mean(entry, na.rm = TRUE)
  )

no_vending_entry_prop
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1      0.377

Among station entrances and exits without vending, approximately 37.7%
allow entrance.

``` r
subway_long =
  subway_df |>
  mutate(
    across(starts_with("route"), as.character)
  ) |>
  pivot_longer(
    cols = starts_with("route"),
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  ) |>
  filter(!is.na(route_name)) |>
  mutate(
    route_number = as.integer(route_number)
  )

subway_long
```

    ## # A tibble: 4,270 × 10
    ##    line     station_name station_latitude station_longitude entry vending
    ##    <chr>    <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ##  1 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  2 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  3 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  4 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  5 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  6 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  7 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  8 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ##  9 4 Avenue 45th St                  40.6             -74.0 TRUE  YES    
    ## 10 4 Avenue 45th St                  40.6             -74.0 TRUE  YES    
    ## # ℹ 4,260 more rows
    ## # ℹ 4 more variables: entrance_type <chr>, ada <lgl>, route_number <int>,
    ## #   route_name <chr>

``` r
a_train_stations =
  subway_long |>
  filter(route_name == "A") |>
  distinct(line, station_name)

nrow(a_train_stations)
```

    ## [1] 60

There are 60 distinct subway stations that serve the A train.

``` r
a_train_ada_stations =
  subway_long |>
  filter(
    route_name == "A",
    ada == TRUE
  ) |>
  distinct(line, station_name)

nrow(a_train_ada_stations)
```

    ## [1] 17

Of the stations that serve the A train, 17 are ADA compliant.

# Problem 2

``` r
excel_sheets("data/202610 Trash Wheel Collection Data.xlsx")
```

    ## [1] "Mr. Trash Wheel"                 "Professor Trash Wheel"          
    ## [3] "Captain Trash Wheel"             "Gwynnda the Good Wheel of the W"
    ## [5] "Sampling Methodology"            "Homes powered note"

``` r
mr_trash =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N700"
  ) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )
```

``` r
professor_trash =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M700"
  ) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    trash_wheel = "Professor Trash Wheel"
  )
```

``` r
gwynnda_trash =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:M700"
  ) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    trash_wheel = "Gwynnda"
  )
```

``` r
trash_wheel_df =
  bind_rows(
    mr_trash |>
      mutate(
        year = as.numeric(year),
        across(
          any_of(c(
            "plastic_bottles",
            "polystyrene",
            "cigarette_butts",
            "glass_bottles",
            "plastic_bags",
            "wrappers",
            "homes_powered"
          )),
          ~ readr::parse_number(as.character(.x))
        )
      ),
    
    professor_trash |>
      mutate(
        year = as.numeric(year),
        across(
          any_of(c(
            "plastic_bottles",
            "polystyrene",
            "cigarette_butts",
            "glass_bottles",
            "plastic_bags",
            "wrappers",
            "homes_powered"
          )),
          ~ readr::parse_number(as.character(.x))
        )
      ),
    
    gwynnda_trash |>
      mutate(
        year = as.numeric(year),
        across(
          any_of(c(
            "plastic_bottles",
            "polystyrene",
            "cigarette_butts",
            "glass_bottles",
            "plastic_bags",
            "wrappers",
            "homes_powered"
          )),
          ~ readr::parse_number(as.character(.x))
        )
      )
  )
```

``` r
professor_total_weight =
  trash_wheel_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarize(
    total_weight = sum(weight_tons, na.rm = TRUE)
  )

professor_total_weight
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         295.

``` r
gwynnda_june_2022 =
  trash_wheel_df |>
  filter(
    trash_wheel == "Gwynnda",
    month == "June",
    year == 2022
  ) |>
  summarize(
    total_cigarette_butts = sum(cigarette_butts, na.rm = TRUE)
  )

gwynnda_june_2022
```

    ## # A tibble: 1 × 1
    ##   total_cigarette_butts
    ##                   <dbl>
    ## 1                 18120

The combined Trash Wheel dataset contains 1,227 observations and 16
variables. Key variables include dumpster number, month, year, date,
weight in tons, volume in cubic yards, counts of different types of
trash, homes powered, and an indicator identifying which Trash Wheel
collected the trash. The three individual datasets were imported from
separate Excel sheets, cleaned to use consistent variable names,
filtered to retain dumpster-specific observations, and combined into one
tidy dataset. The `sports_balls` variable for Mr. Trash Wheel was
rounded to the nearest integer and stored as an integer.

Professor Trash Wheel collected a total of 294.96 tons of trash. Gwynnda
collected 18,120 cigarette butts in June 2022.

\#Problem 3

``` r
unzip(
  "data/data_mci.zip",
  exdir = "data/data_mci"
)
```

``` r
list.files("data/data_mci/data_mci")
```

    ## [1] "mci_amyloid.csv"  "MCI_baseline.csv"

``` r
mci_baseline =
  read_csv(
    "data/data_mci/data_mci/MCI_baseline.csv",
    skip = 1,
    na = "."
  ) |>
  clean_names() |>
  mutate(
    sex = case_match(
      sex,
      0 ~ "Female",
      1 ~ "Male"
    ),
    apoe4 = case_match(
      apoe4,
      0 ~ "Non-carrier",
      1 ~ "Carrier"
    )
  ) |>
  filter(
    is.na(age_at_onset) | age_at_onset > current_age
  )
```

``` r
baseline_summary =
  mci_baseline |>
  summarize(
    participants_recruited = n(),
    developed_mci = sum(!is.na(age_at_onset)),
    average_baseline_age = mean(current_age),
    female_apoe4_carrier_prop =
      mean(apoe4[sex == "Female"] == "Carrier")
  )

baseline_summary
```

    ## # A tibble: 1 × 4
    ##   participants_recruited developed_mci average_baseline_age
    ##                    <int>         <int>                <dbl>
    ## 1                    479            93                 65.0
    ## # ℹ 1 more variable: female_apoe4_carrier_prop <dbl>

After cleaning the baseline demographic data and removing participants
who had already developed MCI by the study baseline, 479 participants
remained in the study. Among these participants, 93 developed MCI during
follow-up. The average baseline age was approximately 65.03 years. Among
women in the study, 30.0% were APOE4 carriers. The `sex` and `apoe4`
variables were recoded from numeric indicators into meaningful
categorical variables, and missing values were coded as `NA`.

``` r
mci_amyloid =
  read_csv(
    "data/data_mci/data_mci/mci_amyloid.csv",
    skip = 1,
    na = c(".", "NA", "Na")
  ) |>
  clean_names()
```

``` r
mci_amyloid_long =
  mci_amyloid |>
  pivot_longer(
    cols = baseline:time_8,
    names_to = "visit",
    values_to = "amyloid"
  ) |>
  mutate(
    visit = case_match(
      visit,
      "baseline" ~ 0,
      "time_2" ~ 2,
      "time_4" ~ 4,
      "time_6" ~ 6,
      "time_8" ~ 8
    ),
    amyloid = as.numeric(amyloid)
  )
```

The amyloid biomarker dataset was imported by skipping the first
descriptive row so that the actual variable names were used as column
names. Missing values were coded as `NA`, and variable names were
standardized. The original dataset was stored in wide format, with
separate columns for biomarker measurements at baseline and at 2-, 4-,
6-, and 8-year follow-up visits. I reshaped the data into long format so
that each row represents one participant at one visit, with separate
variables for participant ID, visit time, and amyloid 42/40 ratio.

``` r
baseline_only =
  mci_baseline |>
  anti_join(
    mci_amyloid,
    by = c("id" = "study_id")
  )

amyloid_only =
  mci_amyloid |>
  anti_join(
    mci_baseline,
    by = c("study_id" = "id")
  )

baseline_only
```

    ## # A tibble: 8 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ## 1    14        58.4 Female        20 Non-carrier         66.2
    ## 2    49        64.7 Male          16 Non-carrier         68.4
    ## 3    92        68.6 Female        20 Non-carrier         NA  
    ## 4   179        68.1 Male          16 Non-carrier         NA  
    ## 5   268        61.4 Female        18 Carrier             67.5
    ## 6   304        63.8 Female        16 Non-carrier         NA  
    ## 7   389        59.3 Female        16 Non-carrier         NA  
    ## 8   412        67   Male          16 Carrier             NA

``` r
amyloid_only
```

    ## # A tibble: 16 × 6
    ##    study_id baseline time_2 time_4 time_6 time_8
    ##       <dbl>    <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
    ##  1       72    0.107 NA      0.107  0.107 NA    
    ##  2      234    0.111  0.111  0.110  0.107  0.109
    ##  3      283    0.113  0.107  0.113  0.108  0.114
    ##  4      380    0.111  0.105  0.107  0.105  0.110
    ##  5      484    0.111  0.111  0.109  0.111  0.107
    ##  6      485    0.106  0.105  0.108  0.107  0.106
    ##  7      486    0.109  0.115 NA      0.110  0.107
    ##  8      487    0.111  0.108  0.110  0.111  0.106
    ##  9      488    0.110  0.112  0.113  0.109  0.109
    ## 10      489    0.115  0.113  0.115  0.116  0.112
    ## 11      490    0.112  0.110  0.111  0.110 NA    
    ## 12      491    0.117  0.114  0.111  0.111  0.111
    ## 13      492    0.110  0.110  0.111  0.109  0.109
    ## 14      493    0.108  0.108  0.109  0.104  0.109
    ## 15      494    0.117  0.110  0.112  0.111  0.109
    ## 16      495   NA      0.105  0.108  0.106  0.103

There were 8 participants who appeared only in the baseline demographic
dataset and 16 participants who appeared only in the amyloid dataset.
Therefore, the two datasets do not contain exactly the same set of
participants, and participants not represented in both datasets will be
excluded when the datasets are combined.

``` r
mci_combined =
  mci_baseline |>
  inner_join(
    mci_amyloid_long,
    by = c("id" = "study_id")
  )
```

The combined demographic and amyloid dataset contains 2,355 observations
and 8 variables. Only participants who appeared in both the cleaned
baseline demographic dataset and the amyloid dataset were retained. Each
participant can contribute multiple observations corresponding to
biomarker measurements at baseline and follow-up visits.

``` r
write_csv(
  mci_combined,
  "data/mci_combined.csv"
)
```
